######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 9 15:21:02 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cpp mywindow.cpp
