######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 9 14:14:37 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
