######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 8 20:44:25 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
