######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 9 11:45:50 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myobject.h
SOURCES += main.cpp myobject.cpp
